[package]
name = "sortery"
version = "0.2.6"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
chrono = "0.4.19"
colored = "2.0.0"
walkdir = "2.3.2"