[package]
name = "sortery"
version = "1.2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.34.0"
colored = "2.0.0"
serde_json = "1.0"
walkdir = "2.3.2"